python main.py \
  --port 18888 \
  --dataset ogbn-products \
  --dropout 0.3 \
  --lr 0.003 \
  --n-partitions 2 \
  --n-epochs 1200 \
  --model gcn \
  --n-layers 3 \
  --n-hidden 256 \
  --log-every 10 \
  --enable-pipeline \
  --use-pp
